
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'NAME CREATE DESTROY\n    grids : expression\n    | empty\n    \n    object : NAME\n    \n    expression : CREATE object NAME\n    | DESTROY object NAME\n    \n    empty :\n    '
    
_lr_action_items = {'CREATE':([0,],[4,]),'DESTROY':([0,],[5,]),'$end':([0,1,2,3,9,10,],[-6,0,-1,-2,-4,-5,]),'NAME':([4,5,6,7,8,],[7,7,9,-3,10,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'grids':([0,],[1,]),'expression':([0,],[2,]),'empty':([0,],[3,]),'object':([4,5,],[6,8,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> grids","S'",1,None,None,None),
  ('grids -> expression','grids',1,'p_grids','grids.py',32),
  ('grids -> empty','grids',1,'p_grids','grids.py',33),
  ('object -> NAME','object',1,'p_object','grids.py',39),
  ('expression -> CREATE object NAME','expression',3,'p_create','grids.py',45),
  ('expression -> DESTROY object NAME','expression',3,'p_create','grids.py',46),
  ('empty -> <empty>','empty',0,'p_empty','grids.py',55),
]
